services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    image: studio-mariadb:local
    container_name: studio-mariadb
    environment:
      MARIADB_DATABASE: resolution_bingo
      MARIADB_USER: studio # move to .env
      MARIADB_PASSWORD: studio # move to .env
      MARIADB_ROOT_PASSWORD: root # move to .env
    ports:
      - "3306:3306" # move to .env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
  nginx:
    # TODO: define nginx entrypoint on localhost 80, 443
  nextjs:
    # TODO: run the app on port 3000
  phpmyadmin:
    # TODO: define helper service (db inspection)

volumes:
  mariadb_data:
