name: nyr-bingo-docker-compose
services:
  mariadb:
    build:
      context: .
      dockerfile: docker/Dockerfile.mariadb
      args:
        MARIADB_PORT: ${DB_PORT:-3306}
    image: nyr-bingo-mariadb:local
    container_name: nyr-bingo-mariadb
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: resolution_bingo
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
  nextjs-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.nextjs
    image: nyr-bingo-nextjs:local
    container_name: nyr-bingo-nextjs
    env_file:
      - .env
    environment:
      DB_HOST: mariadb
      APP_BASE_URL: http://localhost # nginx listens on localhost:80
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.nginx
    image: nyr-bingo-nginx:local
    container_name: nyr-bingo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nyr-bingo.conf:/etc/nginx/conf.d/nyr-bingo.conf:ro
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    depends_on:
      nextjs-app:
        condition: service_healthy
  phpmyadmin:
    image: phpmyadmin:5.2.3
    env_file:
      - .env
    container_name: nyr-bingo-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data: