services:
  mariadb:
    build: # TODO remove build; pull images from registry
      context: .
      dockerfile: docker/Dockerfile.mariadb
    image: studio-mariadb:local
    container_name: studio-mariadb
    environment:
      MARIADB_DATABASE: resolution_bingo
      MARIADB_USER: studio # move to .env
      MARIADB_PASSWORD: studio # move to .env
      MARIADB_ROOT_PASSWORD: root # move to .env
    ports:
      - "3306:3306" # move to .env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
  # nginx:
  #   # TODO: define nginx entrypoint on localhost 80, 443
  # nextjs:
  #   # TODO: run the app on port 3000
  phpmyadmin:
    image: phpmyadmin:5.2.3
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: studio # move to .env
      PMA_PASSWORD: studio # move to .env
    depends_on:
      mariadb:
        condition: service_healthy


volumes:
  mariadb_data:
