services:
  mariadb:
    build: # TODO remove build; pull images from registry
      context: .
      dockerfile: docker/Dockerfile.mariadb
    image: studio-mariadb:local
    container_name: nyr-bingo-mariadb
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: resolution_bingo
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
  # nginx:
  #   # TODO: define nginx entrypoint on localhost 80, 443
  # nextjs:
  #   # TODO: run the app on port 3000
  phpmyadmin:
    image: phpmyadmin:5.2.3
    env_file:
      - .env
    container_name: nyr-bingo-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy


volumes:
  mariadb_data:
