name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'nextjs/specs/**'
      - '**/*.example'
      - '**/*.md'
      - '**/.dockerignore'
      - '**/.gitignore'
      - '**/.modified'
      - '.devcontainer/**'
      
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}
  MARIADB_DOCKERFILE: nextjs/docker/Dockerfile.mariadb
  NGINX_DOCKERFILE: nextjs/docker/Dockerfile.nginx
  NEXTJS_DOCKERFILE: nextjs/docker/Dockerfile.nextjs
  FLYWAY_DOCKERFILE: nextjs/docker/Dockerfile.flyway
  NEXTJS_APP_CONTEXT: nextjs/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create MariaDB image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/mariadb:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/mariadb:${{ github.sha }} \
            -f ${{ env.MARIADB_DOCKERFILE }} \
            ${{ env.NEXTJS_APP_CONTEXT }}
      - name: Push MariaDB image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/mariadb:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/mariadb:${{ github.sha }}
      - name: Create Nginx image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nginx:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nginx:${{ github.sha }} \
            -f ${{ env.NGINX_DOCKERFILE }} \
            ${{ env.NEXTJS_APP_CONTEXT }}
      - name: Push Nginx image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nginx:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nginx:${{ github.sha }}
      - name: Create Next.js image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nextjs-app:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nextjs-app:${{ github.sha }} \
            -f ${{ env.NEXTJS_DOCKERFILE }} \
            ${{ env.NEXTJS_APP_CONTEXT }}
      - name: Push Next.js image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nextjs-app:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/nextjs-app:${{ github.sha }}
      - name: Create Flyway image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/flyway:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/flyway:${{ github.sha }} \
            -f ${{ env.FLYWAY_DOCKERFILE }} \
            ${{ env.NEXTJS_APP_CONTEXT }}
      - name: Push Flyway image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/flyway:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/flyway:${{ github.sha }}
